### ISSUE TITLE
Contribute to Awesom-Surreal Repo

### ISSUE THREAD

**Issue by naisofly** [Ce11an/surrealdb-openai#1]
Hey @Ce11an,

Thanks for sharing this project with the community!
Please do consider contributing it to the Awesome-Surreal repo, perhaps under the [Projects](https://github.com/surrealdb/awesome-surreal?tab=readme-ov-file#projects) section.

Thanks!

**Comment by Ce11an** [comment]
> Hey @Ce11an,
> 
> 
> 
> Thanks for sharing this project with the community!
> 
> Please do consider contributing it to the Awesome-Surreal repo, perhaps under the [Projects](https://github.com/surrealdb/awesome-surreal?tab=readme-ov-file#projects) section.
> 
> 
> 
> Thanks!

Hey @naisofly 👋🏻

Sure! I was speaking to Alexander who suggested that I also make a PR into the Surreal Examples repo. Happy to do both 👍🏻

**Comment by Ce11an** [comment]
I have made a PR for awesome-surreal: https://github.com/surrealdb/awesome-surreal/pull/72 😁

**Comment by naisofly** [comment]
Merged it in. Thanks @Ce11an!
